### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by joshua1** [deepstreamIO/ds-tutorial-express#1]
Hi guys,
this doesnt seem to be working as you get the below error on ```node server.js``` command

```/Users/user/Documents/Sycamore labs/dsExpress/server/node_modules/deepstream.io/src/deepstream.io.js:100
                throw new Error( 'Unknown option "' + key + '"' );
                ^

Error: Unknown option "httpServer"
    at Deepstream.set (/Users/user/Documents/Sycamore labs/dsExpress/server/node_modules/deepstream.io/src/deepstream.io.js:100:9)
    at Object.<anonymous> (/Users/user/Documents/Sycamore labs/dsExpress/server/server.js:13:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)```

**Comment by yasserf** [comment]
@alex-harley we may want to delete this repo and related tutorial!

**Comment by yasserf** [comment]
@joshua this has been removed in 2.0, Rio update accordingly

**Comment by WolframHempel** [comment]
We might want to offer an alternative using an express proxy middleware

2016-12-02 15:16 GMT+01:00 Yasser Fadl <notifications@github.com>:

**Comment by yasserf** [comment]
Yup, simple enough to do

**Comment by misterigl** [comment]
But for now, how do I use deepstream with my express server? The [documentation](https://deepstream.io/tutorials/integrations/other-http/) also still says `deepstream.set( 'httpServer', server );`

**Comment by andrewongi** [comment]
+1
any update?

**Comment by WolframHempel** [comment]
Gents, my apologies for the poor communication around this issue. Deepstream 1.x used to sit on top of the NodeJS http server module and upgraded it to WebSocket connections if possible - this made it possible to use it in conjunction with express which also builds on top of Node HTTP.

deepstream 2.x moves all this functionality into C. It uses a websocket first approach with a thin http implementation sufficient to facilitate the handshake/upgrade procedure and NodeJS bindings. This makes it magnitudes faster and allows for way higher amounts of concurrent connections and message throughput.

As a result, it is no longer possible to share express' http server. Here's what you can do though:

Like any other server it is recommendable to run deepstream in production behind a reverse proxy. This can be something like NginX or HA Proxy as well as IaaS offerings such as AWS Elastic Loadbalancer. This proxy can route traffic from a given path, e.g. /deepstream to the deepstream server and all other traffic to your express server.

**Comment by misterigl** [comment]
Yes, that makes sense, I like the idea. But the express server still connects directly to the deepstream server. doesn't it?
So in a request-response setup with external resources it would be
user -> NginX -> deepstream as request
and then deepstream -> express server / node app -> external resource -> node app -> deepstream -> user as response?
Or can the deepstream server directly interact with JS libraries? Or should I just have a thin node layer on top of the deepstream server?
Sorry for all the questions, still new to it...

**Comment by WolframHempel** [comment]
No worries at all.

Express and deepstream are completely different (and actually have been all along). Express is a HTTP Server library, deepstream is a Websocket server. Deepstream offers request-response functionality on top of its realtime datastore and pubsub capabilities and is built to be integrated with both back and frontends so there's no actual need to use it it conjunction with express

![image](https://cloud.githubusercontent.com/assets/1503717/23246642/6fabd222-f995-11e6-8e1c-50476c5aa020.png)

However you can still use it in conjunction with an HTTP server that can be written in Express (as well as PHP, Python, Ruby or whatever else your heart desires) - all you need is the aforementioned proxy

![image](https://cloud.githubusercontent.com/assets/1503717/23246755/18c987aa-f996-11e6-99f1-fd42b4b3448d.png)
